# Generated by Django 6.0.3 on 2026-03-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=128, unique=True)),
                ("project_name", models.CharField(max_length=256)),
                (
                    "project_group",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("wbs_loaded", models.BooleanField(default=False)),
                ("cbs_loaded", models.BooleanField(default=False)),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("LOCKED", "Locked"),
                        ],
                        default="NOT_STARTED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
