# Generated by Django 6.0.3 on 2026-03-24 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="planning_uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningExtractRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wbs", models.CharField(max_length=256)),
                ("wbs_name", models.CharField(max_length=256)),
                (
                    "activity_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "activity_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("start", models.CharField(blank=True, max_length=256, null=True)),
                ("finish", models.CharField(blank=True, max_length=256, null=True)),
                ("link_01", models.CharField(blank=True, max_length=256, null=True)),
                ("link_02", models.CharField(blank=True, max_length=256, null=True)),
                ("link_03", models.CharField(blank=True, max_length=256, null=True)),
                ("link_04", models.CharField(blank=True, max_length=256, null=True)),
                ("start_date_clean", models.DateField(blank=True, null=True)),
                ("end_date_clean", models.DateField(blank=True, null=True)),
                ("wbs_level", models.IntegerField()),
                (
                    "wbs_level_1",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_2",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_3",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_4",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_5",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_6",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_7",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_8",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_9",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "wbs_level_10",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("cbs_1", models.CharField(blank=True, max_length=256, null=True)),
                ("cbs_2", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "control_account",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "control_account_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.planningupload",
                    ),
                ),
            ],
        ),
    ]
